language: python
python:
  - "3.5"
  - "3.6"
#  - "3.7"

install:
  - "pip install -r file_sort/requirements.txt"
  - "pip install -r file_sort/requirements_test.txt"
  - "pip install ."

script:
  - "nosetests --with-coverage --verbosity=2 file_sort.test.CL_tests"
  #- "python -m unittest file_sort/test/CL_Tests.py"

after_success:
  - codecov